MagaluCloud/terraform-provider-mgc

docs/resources/block_storage_volumes.md
docs/resources/object_storage_buckets.md
docs/resources/virtual_machine_instances.md

This pull request updates the documentation for block storage volumes and object storage buckets. It includes changes to the resource names and provider regions to ensure consistency and accuracy. The documentation now reflects the correct resource names and provider regions for creating, deleting, and managing volumes and buckets.

Update block storage volume and object storage bucket resources documentation

---

go.mod
go.sum
mgc/datasources/mgc_net_public_ip.go
mgc/datasources/mgc_net_security_group.go
mgc/datasources/mgc_net_subnetpool.go
mgc/datasources/mgc_net_vpc.go
mgc/datasources/mgc_net_vpc_subnet.go
mgc/datasources/mgc_net_vpcs_interface.go

- feat: update network datasource implementations to use new sdk
- Tested all outputs with the old and new sdk, no diffs

feat: update network datasource implementations to use new sdk

---

go.mod
go.sum
mgc/datasources/mgc_pf_availability_zones.go

feat: change datasource 'availbility zone' to new sdk

---

mgc/resources/mgc_net_vpcs_interfaces.go

-  refactor Network VPC Interface resource to use new SDK

feat: refactor Network VPC Interface resource to use new SDK 

---

.github/ISSUE_TEMPLATE/bug-report-terraform.md
.github/ISSUE_TEMPLATE/feature-or-enhancement-request.md

- Remove assignees from issue templates for bug reports and feature requests

chore: remove assignees from issue templates for bug reports and feature requests

---

docs/data-sources/kubernetes_nodepool.md
docs/resources/kubernetes_nodepool.md
mgc/datasources/mgc_k8s_nodepool.go
mgc/resources/mgc_k8s_nodepool.go

- Deprecating the Tags field from nodepool datasources and resources

chore: deprecated tags from k8s nodepools resource and datasource

---

docs-extra/index.md
docs/index.md
docs/resources/ssh_keys.md
examples/resources/mgc_ssh_keys/import.sh
mgc/resources/mgc_ssh_keys.go

- Implemented import option for ssh key resource
- Implement new sdk to ssh key resource

feat: implemented ssh key resource with new sdk and import option

---

go.mod
go.sum
mgc/resources/mgc_net_vpcs.go

- Network VPC resource implemented with the mgc sdk

feat: network vpc resource with new sdk

---

mgc/resources/mgc_net_subnetpools.go
mgc/resources/mgc_net_subnetpools_book_cidr.go

- Subnetpool resource changed to use new sdk
- Subnetpool book resource changed to use new sdk

feat: subnetpool and subnetpool book resources change to new sdk

---

mgc/resources/mgc_net_security_groups.go
mgc/resources/mgc_net_security_groups_attach.go
mgc/resources/mgc_net_security_groups_rules.go

- Update all security group resources to use the new SDK
- Security Groups
- Security Groups Attach
- Security Group Rules

feat: update security group resources to use the new sdk

---

go.mod
go.sum
mgc/resources/mgc_net_public_ips.go
mgc/resources/mgc_net_public_ips_attach.go

- Network resources for public ip (public ips and attach public ip) changed to use the new sdk

feat: changed network public ip resources to use the new sdk

---

go.mod
go.sum
mgc/datasources/mgc_k8s_cluster.go
mgc/datasources/mgc_k8s_nodepool.go
mgc/resources/mgc_vm_instances.go
mgc/resources/mgc_vm_interface_attach.go
mgc/resources/mgc_vm_snapshots.go
mgc/tfutil/mgc_k8s_common.go

feat: change vm resource to new sdk

---

docs/resources/kubernetes_cluster.md
go.mod
go.sum
mgc/datasources/mgc_k8s_cluster.go
mgc/datasources/mgc_k8s_nodepool.go
mgc/resources/mgc_k8s_cluster.go
mgc/resources/mgc_k8s_nodepool.go
mgc/tfutil/mgc_k8s_common.go
tests/k8s/kubernets.tf
tests/k8s/provider.tf

- K8s resources (Cluster and Nodepool) upgraded to use the new sdk
- Small fixes in the K8s datasources
- K8s Cluster Async mode deprecated

feat: change k8s resources to use the new sdk

---

mgc/resources/mgc_container_registries.go
tests/container-registry/main.tf

- Container Registries resource changed to use the new sdk

feat: change container registry resource to use the SDK

---

go.mod
go.sum
mgc/datasources/mgc_bs_volume.go
mgc/datasources/mgc_bs_volumes.go
mgc/resources/mgc_bs_snapshots.go
mgc/resources/mgc_bs_volume_attach.go
mgc/resources/mgc_bs_volumes.go

- Block storage resources changed to use the new SDK
- Block storage datasources adjusted to reflect the correct pointers

feat: block storage resources changed to use the new sdk

---

.gitignore

- Added zed config folder to gitignore

chore: add zed config folder to gitignore

---

Makefile
README.md

chore: Enhance README with comprehensive documentation and examples

---

.github/workflows/unit-tests.yml
sonar-project.properties

feat: add sonar

---

tests/object-storage/main.tf
tests/object-storage/object_storage.tf

- Improve object storage tests files

chore: improve object store testing

---

mgc/resources/mgc_vm_instances.go

fix: vm - parse error on instance creation

---

mgc/resources/mgc_k8s_nodepool.go
mgc/resources/mgc_net_public_ips_attach.go
mgc/resources/mgc_net_vpcs_subnets.go
tests/k8s/kubernets.tf

- Improve code consistence using terraform State get for creating resources.

chore: Fix node pool resource handling and schema definitions

---

mgc/provider.go
mgc/tfutil/region_validator.go
mgc/tfutil/regions.go
mgc/tfutil/regions_test.go

feat: flexible url

---

mgc/provider.go

- Added os and arch info about the os in the user agent.
example:
```
User-Agent: MgcTF/dev (linux; amd64)
```

chore: user agent with os and arch data

---

release.yaml

- Fix an incorrect character in the version variable

fix: Remove trailing double quote from ldflags in release.yaml

---

docs/resources/network_security_groups_rules.md
go.mod
go.sum
mgc/datasources/mgc_net_security_group.go
mgc/resources/mgc_net_security_groups_rules.go
tests/virtual-machine/main.tf

- Update SDK version to v0.3.29
- Remove Network Rules field id group remote

fix: update sdk to v0.3.29 and remove RemoteGroupId field from security group rules

---

docs-extra/guides/vm-network.md
docs/guides/vm-network.md
docs/resources/virtual_machine_instances.md
examples/resources/mgc_virtual_machine_instances/resource.tf
examples/resources/mgc_virtual_machine_instances/terraform.tfstate

- Added a new documentation file to terraform provider about how to create virtual machines with public ips

chore: Added documentation about vm creation with public ip

---

mgc/resources/mgc_net_vpcs.go
tests/network/main.tf

- Improved the error message when pooling a vpc resource with error.

feat: improved network vpc error message when pooling the resource

---

docs-extra/guides/backend-tsstate.md
docs/guides/backend-tsstate.md

- Adjust the endpoints struct to the lastest version of terraform

chore: improve terraform s3 backend documentation

---

docs-extra/guides/network-basics.md
docs-extra/guides/vm-network.md
docs/data-sources/network_subnetpool.md
docs/data-sources/network_subnetpools.md
docs/guides/network-basics.md
docs/guides/vm-network.md
docs/resources/network_subnetpools.md
examples/resources/mgc_network_subnetpools/resource.tf
mgc/datasources/mgc_net_subnetpool.go
mgc/datasources/mgc_net_subnetpools.go
mgc/resources/mgc_net_subnetpools.go
tests/network/main.tf
tests/virtual-machine-interface-attach/main.tf

- Removed from resource, datasources and documentation the field type from subnetpools
- This is fild is for internal use only and will be removed from the public API

fix: removed network subnetpool type field

---

docs-extra/guides/vm-network.md
docs-extra/guides/vm-user-data.md
docs-extra/guides/vm-windows.md
docs/guides/vm-network.md
docs/guides/vm-user-data.md
docs/guides/vm-windows.md
examples/provider/provider.tf
tests/k8s/kubernets.tf
tests/k8s/provider.tf

- Created more doc guides
- User data in VM
- Windows VM
- Vm networking
- Others small improviments in the docs

feat: added more docs about vm networt, windows, userdata and others small adjustments

---

docs-extra/guides/dbaas-creation.md
docs/guides/dbaas-creation.md

- New guide on how to create a Instance, Cluster and Replicas

doc: DBaaS v2 guide

---

docs-extra/guides/network-basics.md
docs-extra/guides/vm-network.md
docs/guides/network-basics.md
docs/guides/vm-network.md

- Improve network guide for vnic attach

docs: improve network vnic attach documentation

---

docs-extra/guides/dbaas-migration.md
docs/guides/dbaas-migration.md

- New guide on how to migrate the dbaas instance resource to v2

doc: new doc for dbaas v2 migration

---

tests/dbaas/main.tf

fix: restore dbaas v2 tests

---

docs/resources/dbaas_parameter_groups.md
mgc/resources/mgc_dbaas_parameter_groups.go

Changes engine referral on parameter groups creation from ID to name + version, as it's done on db instances 
Manual creation, update and delete tests

Parameter groups with engine name + version

---

docs-extra/index.md
docs/index.md
mgc/provider.go
tests/object-storage/main.tf

- Removed the deprecated OS Vars in the terraform provider.

chore: removed deprecated provider OS envs

---

docs/data-sources/kubernetes_clusters.md
docs/data-sources/kubernetes_nodepool.md
docs/resources/kubernetes_cluster.md
docs/resources/kubernetes_nodepool.md
mgc/datasources/mgc_k8s_clusters.go
mgc/datasources/mgc_k8s_nodepool.go
mgc/resources/mgc_k8s_cluster.go
mgc/resources/mgc_k8s_nodepool.go
mgc/tfutil/mgc_k8s_common.go
tests/k8s/kubernets.tf

- Removing deprecated fields from provider config
- Removing deprecated fields from k8s

feat: removing deprecated fields from provider and k8s resource

---

mgc/resources/mgc_bs_volumes.go

fix: block storage - isError

---

docs/resources/kubernetes_cluster.md
docs/resources/kubernetes_nodepool.md
examples/resources/mgc_kubernetes_cluster/resource.tf

Resolves issue #178
Improve kubernetes docs
Once It's just a doc change, I didn't build and test it.

Update Kubernetes docs

---

.github/workflows/docs-checks.yml
.github/workflows/go-checks.yml
.github/workflows/release.yaml
.github/workflows/unit-tests.yml

chore: change workflows

---

docs/resources/dbaas_instances.md
mgc/resources/mgc_dbaas_instances.go

##What does this PR do?
- feat: dbaas instace restore from snapshot feature

feat: dbaas instace restore from snapshot feature

---

mgc/resources/mgc_k8s_cluster.go
mgc/resources/mgc_k8s_nodepool.go

- Added the pooling when deleting k8s cluster and nodepools

feat - added delete pooling to k8s cluster and nodepool

---

docs-extra/guides/dbaas-creation.md
docs/guides/dbaas-creation.md
mgc/resources/mgc_dbaas_instances.go

style: fix typo

---

docs/data-sources/kubernetes_cluster.md
docs/resources/kubernetes_cluster.md
mgc/kubernetes/datasource_cluster.go
mgc/kubernetes/datasource_cluster_test.go
mgc/kubernetes/resource_cluster.go
tests/dbaas/main.tf
tests/k8s/kubernets.tf

- Added support new field `CNI` in kubernets cluster resource and datasource

feat: Add CNI support to Kubernetes cluster resource and data source

---

mgc/database/resource_instances.go

Refactor DBaaS Instance Resze into only one request.
Created, Resized individually instance-type-id and volume, and both simultaneously.

refactor: dbaas instance resize
